security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    providers:
        in_memory:
            memory: ~

        entity_provider:
            id: user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        oauth_token:
            pattern: ^/oauth/v2/token
            security: false

        oauth_authorize:
            pattern: ^/oauth/v2/auth
            form_login:
                check_path: oauth_login_check
                login_path: oauth_login

        api:
            pattern: ^/api
            fos_oauth: true
            stateless: true
            anonymous: false